name: Job Monitor

on:
  workflow_dispatch: # 支持手动点击运行
  schedule:
    - cron: '0 2,10 * * *' # 每天北京时间 10:00 和 18:00 自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: Run Script
        env:
          PUSHDEER_KEY: ${{ secrets.PUSHDEER_KEY }}
          UPWORK_RSS: ${{ secrets.UPWORK_RSS }}
        run: python job_monitor.py
